### ISSUE TITLE
Creating CentOs 7 Live CD Failed on Aarch64.

### ISSUE THREAD

**Issue by xxAllanxx3** [livecd-tools/livecd-tools#100]
I was trying to create customized Cent OS 7 Live Cd for aarch64 based system but livecd-creator tool is keep exiting out with the tool is arch specific. I am using 23.4 version.

**Comment by fedya** [comment]
any news here?

**Comment by Conan-Kudo** [comment]
AArch64 support was just merged into mainline and will be part of the livecd-tools v28 release coming out today.
