### ISSUE TITLE
Unable to run 'usr/bin/firewall-offline-cmd' Centos 7.4.1708

### ISSUE THREAD

**Issue by Serienmorder** [livecd-tools/livecd-tools#107]
There was a previous bug with linux-firmware 58 that I was able to maneuver around by adding 62 to my repository. But I still receive the following error in the attached file.

[log.txt](https://github.com/livecd-tools/livecd-tools/files/2353358/log.txt)

**Comment by Serienmorder** [comment]
using livecd-tools-21.4-2.el7.x86_64.rpm

**Comment by Conan-Kudo** [comment]
This has been fixed in livecd-tools since 2caa3f01d10e21fd42482fcf0c84a63fd0388639.
