### ISSUE TITLE
TypeError: package() got an unexpected keyword argument 'ops'

### ISSUE THREAD

**Issue by techduderavi** [livecd-tools/livecd-tools#118]
Getting below error when trying to build CentOS 7.6.
1810 live cd

Losetup remove /dev/loop0
Traceback (most recent call last):
  File "tools/livecd-creator", line 258, in <module>
    sys.exit(main())
  File "tools/livecd-creator", line 241, in main
    creator.package(ops=ops)
TypeError: package() got an unexpected keyword argument 'ops'

**Comment by jiopaley** [comment]
I'm seeing the same error in v27.1

**Comment by Conan-Kudo** [comment]
@jiopaley What distribution are you running livecd-tools on?

**Comment by jiopaley** [comment]
Sorry my mistake. My pythonpath was referring to a different version of the imgcreate module. version 27.1 works for me.

**Comment by Conan-Kudo** [comment]
Ah, good. Then I'll consider this fixed.
