### ISSUE TITLE
Message error 'No such file or directory ' when executing command 'livecd-iso-to-disk'.

### ISSUE THREAD

**Issue by Ricky-Tigg** [livecd-tools/livecd-tools#121]
OS: _Fedora_; Component: livecd-iso-to-mediums.x86_64 1:26.1-1.fc29 @updates

Plug-in to system hardware an **external** storage device – here an _EXT4_-formatted USB  –.
Commands executed:
```
$ df -HTt ext4 | grep /run/media/
/dev/sdd1                ext4  7.9G   36M  7.4G   1% /run/media/user/USB
$ umount /dev/sdd1
# ls
debian-9.7.0-amd64-DVD-3.iso
# livecd-iso-to-disk debian-9.7.0-amd64-DVD-3.iso /dev/sdd1
mount: /run/imgtmp.5nuVrc: mount failed: No such file or directory.
Cleaning up to exit...
```
As the output suggests the disk image cannot be mounted to sdd1.

**Comment by Conan-Kudo** [comment]
Debian media is formatted differently, and thus is currently incompatible with `livecd-iso-to-disk`.

**Comment by Ricky-Tigg** [comment]
I learned something.; could you mean that even as a Live ISO, since supplied by Debian,  it is known to be incompatible with the use of function `livecd-iso-to-disk`? Output of involved install ISO:
```
$ file -b debian-9.7.0-amd64-DVD-3.iso
ISO 9660 CD-ROM filesystem data 'Debian 9.7.0 amd64 3'
```
