### ISSUE TITLE
Flatpak or Snap support

### ISSUE THREAD

**Issue by khoitd1997** [livecd-tools/livecd-tools#125]
Hi is it possible to install snap or flatpak package during the creation of livecd? If not, is there a plan to support it? I have been trying to run snap or flatpak install during the %post section of kickstart but that doesn't seem to work.

**Comment by Conan-Kudo** [comment]
I'm honestly not sure how to do preloading flatpaks or snaps during a live image build...

**Comment by zyga** [comment]
I don't know enough about livecd-tools to answer but I can tell you the snapd side:

Snapd supports the concept of seeding. When certain files are placed on the filesystem and snapd is started it will ingest those files and install the snaps they describe on the first run. This is used by Ubuntu's live media _and_ the installed system.

**Comment by zyga** [comment]
You can learn more about seeding here: https://forum.snapcraft.io/t/seed-yaml-documentation/3050

Note that seeding must be assisted by "snap prepare", that is you need to ask snapd to prepare a seed filesystem.
