### ISSUE TITLE
app calls in scripts

### ISSUE THREAD

**Issue by latot** [livecd-tools/livecd-tools#13]
Hi, this more of compatibility issue with other distros and with structures of files and directories , a lot of scripts of this tools use calls like

'/sbin/parted'

but not all the installations use that directory, its posible call directly with the app name?

'/sbin/parted' -> 'parted'

and with necesary rutes use the command which instead a direct path?

Thx.

**Comment by vpodzime** [comment]
Sounds like a good idea to me.

**Comment by latot** [comment]
Hi, actually i think is necessary this, but ideally use it in all files, because now i even can't install this because calls like sh are written with path (/bin/sh)....

**Comment by FGrose** [comment]
See pull request #53 
Untested for kickstart.py, creator.py, live.py, edit-livecd, mkbackup, & mkbiarch.

**Comment by latot** [comment]
Hi, i prefer ```#! /bin/bash```, checking this:
https://stackoverflow.com/questions/10591086/shell-script-headers-bin-sh-vs-bin-csh, there show part of this.

Thx. Cya.

**Comment by Conan-Kudo** [comment]
This is now fixed as of livecd-tools v25.0.
