### ISSUE TITLE
heads up, PR to drop legacy swap startup in fedora kickstarts

### ISSUE THREAD

**Issue by cmurf** [livecd-tools/livecd-tools#133]
I just want to give livecd-tools folks a heads up in case they want to nack this PR:
https://pagure.io/fedora-kickstarts/pull-request/544#

Anaconda now automatically starts swap on ZRAM on low memory systems, so doing `swapon` for existing swap partitions isn't necessary. But then I thought, oh maybe someone uses livecd-iso-to-disk for a portable system and needs/wants --swap-size-mb flag to create a swapfile, and if so my PR, if merged, would mean the swapfile is silently not used.

Two alternatives to the proposed clean up:
Changing the swapon section to apply only to /run/initramfs/live/\${livedir}/swap.img so that no other swap partition or LV is enabled.

Drop --swap-size-mb in favor of e.g. --swapforce which would add two boot parameters `inst.zram=1 systemd.wants=zram.service`. I've tested this on a VM with 3G RAM, and the first option causes anaconda/zramswapon to be forced even if memory is more than 2G, and the second directly starts zram.service rather than requiring anaconda to be launched.

Using swap on ZRAM will give way better performance than swapfile on flash drive.

**Comment by Conan-Kudo** [comment]
@FGrose Can you take a look at this and see what we need to do, if anything?

**Comment by cmurf** [comment]
re: `inst.zram=1 systemd.wants=zram.service` triggers anaconda's swap on zram service unit. 

There's an unrelated zram package in Fedora being used mainly by IoT folks right now
https://src.fedoraproject.org/rpms/zram and also there

And work on a generic solution in systemd
https://github.com/systemd/zram-generator

Ideally the systemd zram generator can be a generic solution that can be something included in base, eventually, and use that instead of swapfiles which have got to be really slow on a USB stick.

Until the dust settles, I don't think it makes sense to flat out break livecd-tools --swap-size-mb, so looking at:
https://pagure.io/fedora-kickstarts/pull-request/544#request_diff
Does it make sense to keep lines 5, 12-14 instead of what I've proposed? Pretty sure that means only a swapfile on a LiveOS as created by livecd-tools would be enabled.

**Comment by Conan-Kudo** [comment]
> Until the dust settles, I don't think it makes sense to flat out break livecd-tools --swap-size-mb, so looking at:
https://pagure.io/fedora-kickstarts/pull-request/544#request_diff
Does it make sense to keep lines 5, 12-14 instead of what I've proposed? Pretty sure that means only a swapfile on a LiveOS as created by livecd-tools would be enabled.

Yeah, that probably makes sense...

**Comment by cmurf** [comment]
Another factor in favor of swap on zram, and livecd-tools dropping swapfiles in favor of it, is the security angle. The swapfile isn't encrypted.

**Comment by cmurf** [comment]
Closed this
https://pagure.io/fedora-kickstarts/pull-request/544#
Opened this
https://pagure.io/fedora-kickstarts/pull-request/553#
