### ISSUE TITLE
dracut-install:  livecd-creator  dracut glitch

### ISSUE THREAD

**Issue by cherusk** [livecd-tools/livecd-tools#137]
Running on:

```
cat /etc/os-release 
NAME=Fedora
VERSION="30 (Thirty)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Thirty)"
```
That:
```
# livecd-creator  -c ./universal.ks --logfile=log -v -
```
Base on [repo](https://github.com/cherusk/recovery). I'm merely adding custom pkgs in the ks cnfg as you can see there, so certainly no install interference to expect.

It leads to dracut issue, perceivable in log:
> [...]
> dracut: No '/dev/log' or 'logger' included for syslog logging
> dracut-install: ERROR: installing 'sr_mod'
> dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.s1Hfen/initramfs --kerneldir /lib/modules/5.2.11-200.fc30.x86_64/ -m sr_mod sd_mod ide_cd cdrom =ata sym53c8xx aic7xxx ehci_hcd uhci_hcd ohci_hcd usb_storage usbhid uas firewire-sbp2 firewire-ohci sbp2 ohci1394 ieee1394 mmc_block sdhci sdhci-pci pata_pcmcia mptsas virtio_blk virtio_pci virtio_scsi virtio_net virtio_mmio virtio_balloon virtio-rng
> dracut-install: ERROR: installing 'ext4'
> dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.s1Hfen/initramfs --kerneldir /lib/modules/5.2.11-200.fc30.x86_64/ -m vfat msdos isofs ext4 xfs btrfs squashfs
> [...]

When I run this dracut-install invocation manually. Getting:
```
:~# /usr/lib/dracut/dracut-install -D /var/tmp/dracut.s1Hfen/initramfs --kerneldir /lib/modules/5.2.11-200.fc30.x86_64/ -m vfat msdos isofs ext4 xfs btrfs squashfs
**dracut-install: Environment variable DRACUT_FIRMWARE_PATH is not set**
```
Any hints? Presume not doing anything oddish here. :)
Thanks!

**Comment by cherusk** [comment]
Tried to work around now via **editliveos**, not building but altering from upstream available image:

$ sudo editliveos --refresh-only --kickstart universal.ks --noshell ./Fedora-Cinnamon-Live-x86_64-30-1.2.iso --output ./outcome/

Crashing with:
cp: cannot stat '/var/tmp/editliveos-ecys2f4c/install_root/usr/share/licenses/*-release/*': No such file or directory

LiveOS edit has completed.

```
> Process duration: 00:02:57
> Traceback (most recent call last):
>   File "/usr/bin/editliveos", line 2438, in <module>
>     sys.exit(main())
>   File "/usr/bin/editliveos", line 2350, in main
>     editor.install_rpms()
>   File "/usr/bin/editliveos", line 2107, in install_rpms
>     (name, baseurl, mirrorlist, proxy, inc, exc, cost) = repo
> ValueError: too many values to unpack (expected 7)
```
Might deserving separate issue, but illustrating the tools pkg seems not so mature onf FED30 latest. :(

**Comment by FGrose** [comment]
Please try the current master branch.  Installing packages was reworked in commit 82548ae30312003d81ec53ed585f97860da934b8.

**Comment by cherusk** [comment]
Apears working as you specified @FGrose for **editliveos**, only had to %packages --ignoremissing.

Still, will leave open for the **livecd-creator** issue originally brought up.
