### ISSUE TITLE
Non-whole device paths not to be validated in commands when '--format --reset-mbr' is mentionned

### ISSUE THREAD

**Issue by Ricky-Tigg** [livecd-tools/livecd-tools#142]

**Comment by Ricky-Tigg** [comment]
Application does allow  in command  `sudo livecd-iso-to-disk --format --reset-mbr <name>.iso /dev/sdb1` mentions such as  /dev/sdb1, thus implicitly does validate them as legitimate for execution. Despite that, once command gets executed, application does explicitly mention `WARNING: This will DESTROY ALL DATA on: /dev/sdb `!.

Which one of the implicit or explicit effect to trust then? It seemed saf at firste to interpret that sdb1 precedes sdb thus warning can be ignored. Though execution of command to its process's end, indicates afterwards that path sdb1 won't be honoured. Prohibiting in commands paths that do not represent whole device partitions, would have avoided for sure source of confusion.

**Comment by FGrose** [comment]
The requested test for only whole device paths on --format requests was implemented in PR #176.
