### ISSUE TITLE
toram/docache support

### ISSUE THREAD

**Issue by birdie-github** [livecd-tools/livecd-tools#147]
It would be really great to be able to copy the livecd image into RAM.

Why it could be useful:
- Working with a live CD becomes a whole lot faster 'cause RAM access times are minimal vs any storage
- It'll become possible to remove the boot storage from the PC after booting

Debian calls this option `toram`, gentoo calls it `docache` - I guess we could use both.

**Comment by FGrose** [comment]
For Fedora, `rd.live.ram` is the kernel command line option in dracut. See https://github.com/dracutdevs/dracut/blob/master/dracut.cmdline.7.asc#booting-live-images.
