### ISSUE TITLE
livecd-tools cannot create aarch64 media

### ISSUE THREAD

**Issue by jffree** [livecd-tools/livecd-tools#160]
Are threr any plan to support aarch64 ?

**Comment by fedya** [comment]
+ interesting too

**Comment by Conan-Kudo** [comment]
I'm looking into this now and hopefully will have a fix for this soon...

**Comment by fedya** [comment]
Tried today to create aarch64 iso on aarch64 hardware and got 

`Error creating Live CD : Bootloader configuration is arch-specific, but not implemented for this arch!`

**Comment by Conan-Kudo** [comment]
I am working on an implementation, I hope to have a PR up soon (in a couple of days).

**Comment by fedya** [comment]
any news here? Want to test it.

**Comment by mikhailnov** [comment]
@Conan-Kudo What is the current progress? I think it is a queation of a couple of if-else switches, if you need help, we may find some engineering resources or may be try to somehow help with testing on hardware, but what is the current status?

**Comment by zhujing3** [comment]
> I am working on an implementation, I hope to have a PR up soon (in a couple of days).

plz send your PR  -_-

**Comment by Pro-pra** [comment]
https://github.com/livecd-tools/livecd-tools/pull/170
