### ISSUE TITLE
livecd-creator: EFI should check for shimx64.efi as well

### ISSUE THREAD

**Issue by space88man** [livecd-tools/livecd-tools#165]
Version: 27.1-4.el8

UEFI installations of CentOS 8 only install `/boot/efi/EFI/centos/shimx64.efi` and not `/boot/efi/EFI/centos/shim.efi`.

The EFI detection code seems  to check only for `shim.efi`.

**Comment by dreddpenguin** [comment]
Has or will this issue be addressed? CentOS 8.x shim-x64 no longer provides shim.efi, only shimx64.efi.
yum provides shim.efi only shows results for shim-ia32 which is the wrong arch and results in a traceback.

**Comment by Conan-Kudo** [comment]
This is something I intend to fix for the next release. 👍🏾

**Comment by dreddpenguin** [comment]
> This is something I intend to fix for the next release. 👍🏾

Is there any idea of an ETA?

**Comment by Conan-Kudo** [comment]
I'll probably merge #182 in absence of any feedback from anyone and include a fix for this for the next release this weekend.

**Comment by dreddpenguin** [comment]
Is there any update for ETA on the merge for #182?

**Comment by Conan-Kudo** [comment]
It was merged and released as livecd-tools v28.

**Comment by dreddpenguin** [comment]
Can you point me to install directions for v28? I'm only used to getting RPM from repo.

**Comment by Conan-Kudo** [comment]
I've submitted it to EPEL: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-11822cc291
