### ISSUE TITLE
Missing support for `authselect`

### ISSUE THREAD

**Issue by Conan-Kudo** [livecd-tools/livecd-tools#203]
The `authconfig` command is deprecated and slated for removal soon, we need to have `authselect` implemented to replace it.

This has been available since F28/EL8.

**Comment by Conan-Kudo** [comment]
See https://fedoraproject.org/wiki/Changes/RemoveAuthselectCompatPackage

**Comment by Conan-Kudo** [comment]
Looks like @pbrezina is working on this in #205

**Comment by bcl** [comment]
The related pykickstart PR is https://github.com/pykickstart/pykickstart/pull/387

**Comment by Conan-Kudo** [comment]
This is now done with 9c7f40e7edae3475be9a0b8afd7b390a7ad3bfbc.
