### ISSUE TITLE
Problem using livecd-iso-to-disk with gpt/ext4 key.

### ISSUE THREAD

**Issue by BeRoots** [livecd-tools/livecd-tools#211]
Hello.
I tried to create a persistent usb key of fedora 34 on a usb key fomated with gparted to have a GPT partition table and a simple EXT4 partition. But impossible to create home overlay and persistent overlay greater than 4095Mo.

![screenshoot](https://pasteall.org/media/d/4/d468f7f4fe0a4515fbcec2ae3d815b86.png)

The commands like `sudo livecd-iso-to-disk --format --efi --timeout -1 --totaltimeout 0 --home-size-mb 3584 --crypted-home --overlay-size-mb 3584 /mnt/vm-fat/iso-src/Fedora-Workstation-Live-x86_64-34-1.2.iso /dev/sdb` Works.
But with size upper than 4095 on any overlay I have the error:
```
        ALERT:
        An overlay size greater than 4095 MiB
        is not allowed on VFAT formatted filesystems.
```
Idem with command like ` sudo livecd-iso-to-disk --format --efi --timeout -1 --totaltimeout 0 --home-size-mb 1024 --crypted-home --overlayfs ./Fedora-Workstation-Live-x86_64-34-1.2.iso /dev/sda`
```
        ALERT:
        If the target filesystem is formatted as vfat or msdos, you must
        specify an --overlay-size-mb <size> value for an embedded overlayfs.

        Exiting...
```

TO REPRODUCE:
- Get a live iso image of an OS
- Create a GPT partition table from gparted
- Add a full sized EXT4 partition on it
- try to run `sudo livecd-iso-to-disk --format --efi --timeout -1 --totaltimeout 0 --home-size-mb 4096 --crypted-home --overlay-size-mb 4096 /mnt/vm-fat/iso-src/Fedora-Workstation-Live-x86_64-34-1.2.iso /dev/sdb`

**Comment by FGrose** [comment]
This is a known limitation with the released versions.  Try the lastest version in main (see PR #176 ), or the pending PR #207 https://github.com/FGrose/livecd-tools/blob/9287db87fcfdf892c5f3a3bec0bcdff8b266931e/tools/livecd-iso-to-disk.sh

**Comment by BeRoots** [comment]
Ok. Thanks for the feedback. I close the issue.
