### ISSUE TITLE
Put overlay files on a separate partition

### ISSUE THREAD

**Issue by mdomsch** [livecd-tools/livecd-tools#212]
On FAT32-formatted file systems, the overlay files have a maximum size of 4095MB each.  If the USB device had a separate partition (e.g. partition 4), it could contain an ext4 file system, on which the overlay files could be created and could then consume all available space without being constrained to 4095MB each.  The bootable partition 1 FAT32 file system could then be reduced in size to just more than enough to hold the boot files and root file system, leaving plenty of space for the overlay partition.

**Comment by FGrose** [comment]
See PR #176 , now merged, which defaults to provide an EFI System Partition separate from the primary image partition.
