### ISSUE TITLE
GPG verification for installed RPMs?

### ISSUE THREAD

**Issue by cbs228** [livecd-tools/livecd-tools#225]
Does livecd-creator offer an interface for configuring the GPG keys to use for RPM verification? If it does, I cannot find it.

dnf supports the [`gpgkey`](https://dnf.readthedocs.io/en/latest/conf_ref.html?highlight=gpg#repo-options) option for setting the signing key directly. I do not see this option in places like [`imgcreate.creator.install()`](https://github.com/livecd-tools/livecd-tools/blob/034c5e8368484647e1ef2ef24e927f1af1f39215/imgcreate/creator.py#L697). Perhaps this is because the kickstart [`repo`](https://docs.fedoraproject.org/en-US/fedora/latest/install-guide/appendixes/Kickstart_Syntax_Reference/#sect-kickstart-commands-repo) command is missing this option.

Does anyone know what happens when no GPG keys are configured? Are keyrings or trust delegated to the host OS? Does dnf skip signature-checking or perform verification in an insecure manner? (Such as relying on a TLS chain-of-trust at build time.) Some insight would be appreciated here. If we could end up in a situation where signature checking is not performed, we should probably try to address this.

**Comment by Conan-Kudo** [comment]
Right now, GPG checks are disabled because we can't pass in any keys. #14 adds the ability to do this, but it's blocked on pykickstart support...

**Comment by cbs228** [comment]
Good to know, thank you. I'm not sure there's too much optimism surrounding the prerequisite pykickstart/pykickstart#32, which has been closed for several years now. Attempts to add this to the kickstart dialect also have [not progressed](https://hackmd.io/HU2j0hF9RZSqoaaloE7YFA).

What about potentially accepting keyrings or fingerprints as CLI arguments? This isn't as clean as putting it in kickstart, but it may be better than nothing.

**Comment by Conan-Kudo** [comment]
I'd be open to it, but we'd need to preserve the default behavior.
