### ISSUE TITLE
livecd-iso-to-pxeboot: pxelinux.0 may require ldlinux.c32

### ISSUE THREAD

**Issue by tomhughes** [livecd-tools/livecd-tools#23]
In recent versions of syslinux (not sure how recent but at least F22 and later have this problem) the `pxelinux.0` binary will not function on it's own but will try and load `ldlinux.c32` so `livecd-iso-to-pxeboot` should copy that into the tftpboot tree alongside `pxelinux.0`.

**Comment by bcl** [comment]
Could you give pull #25 a try?

**Comment by Conan-Kudo** [comment]
Fixed with 6d6f43f17fdfaa4aab42ed69f3587f40329c09be.
