### ISSUE TITLE
Fedora disc images reported as not supported

### ISSUE THREAD

**Issue by Ricky-Tigg** [livecd-tools/livecd-tools#241]
Hello. Disc images available:
```
$ file -b Fedora-{Workstation-Live-x86_64-36-1.5,Server-dvd-x86_64-36-1.5}.iso
ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'Fedora-WS-Live-36-1-5' (bootable)
ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'Fedora-S-dvd-x86_64-36' (bootable)
```
Despite those images are Fedora and then to be considered as supported by this tool, while running `livecd-iso-to-disk --multi <disc_image> <device>`, `Supported ISO: no` is reported in the output, Isn't that `yes` that is expected instead of `no`?

**Comment by FGrose** [comment]
`Supported ISO: no` is a feature of `implantisomd5` and `checkisomd5`.

from `man implantisomd5`:
``` txt
--supported-iso
                 Indicate that the image will be written to a "supported" media,
                 such as pressed CD.  On Red Hat-based Anaconda installers, this
                 bypasses the prompt to check the CD.
```
This has been standard.

**Comment by Ricky-Tigg** [comment]
That answer would have remained unknown to me as i would not have guessed that the root of that state had to be sought outside the context of `man livecd-iso-to-disk`. Hoping that a person being in the same position as the one i was ini will be lucky to find an answer here if ever. Otherwise a duplicate of this subject might be created.
