### ISSUE TITLE
Missing menu.c32 at boot because inconsistent syslinux.cfg

### ISSUE THREAD

**Issue by lesnake** [livecd-tools/livecd-tools#34]
After generating an image, I use livecd-iso-to-disk script to make a bootable usb key.
The process is successfull.
But the reboot fail on legacy (not EFI) mode because menu.c32 is missing.

Steps to reproduce : 
- create an image so that there is a vesamenu.c32 in the file system
- "burn" on usb key
- reboot

My investigations shows :
- there is a vesamenu.c32 where there should be menu.c32
- changing the first line from "default menu.c32" to "default vesamenu.c32" allows grub loading and booting
- that syslinux.cfg does not get updated when the livecd-iso-to-disk script selects which c32 file to put in the image

Attached is a patch that allows the script to work.
[livecd-iso-to-disk.patch.txt](https://github.com/rhinstaller/livecd-tools/files/361821/livecd-iso-to-disk.patch.txt)
Yet, I have not tested all the branches.

**Comment by lesnake** [comment]
By branches, I mean the possible logical branches in the script, not development branches.

**Comment by Conan-Kudo** [comment]
This should be now fixed in ead767e0e94a2dd115fa62745eaac9b2a8af1418.
