### ISSUE TITLE
Using livecd-iso-to-disk option --format results in non-booting USB stick

### ISSUE THREAD

**Issue by axelsommerfeldt** [livecd-tools/livecd-tools#42]
When using livecd-iso-to-disk option --format under Fedora 25 the result is a non-booting USB stick ("Failed to load ldlinux.c32"). The cause is Fedora 25 formatting ext4 partitions with "64bit" feature as default, but this does not work with the current version of syslinux.

See also: http://www.syslinux.org/wiki/index.php?title=Filesystem

> As of Syslinux 6.03, "pure 64-bits", compression and/or encryption are not supported.
> ..
> To manually disable the "64bit" feature when creating ext4 volumes, use  -O ^64bit  in the mke2fs (or equivalent) command."

A solution would be changing line 562 of livecd-iso-to-disk from

` $mkfs -L $label $TGTDEV`

to

` $mkfs -L $label -O ^64bit $TGTDEV`

See also: https://ask.fedoraproject.org/en/question/99405/livecd-iso-to-disk-creates-usb-disk-which-failed-to-load-ldlinuxc32/

**Comment by Conan-Kudo** [comment]
Fixed with 5ac2ecb103d0af2a1e7613bc856f81ae676697eb.
