### ISSUE TITLE
Swap image cannot be used('--swap-size-mb' option)

### ISSUE THREAD

**Issue by ashegoulding** [livecd-tools/livecd-tools#44]
Swap image cannot be used as the fs is mounted read-only. Adding "rw" to kernel cmdline solves this problem. Maybe the script should add that cmdline arg if '--swap-size-mb' option is used.

Reported on [Redhat bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1418315) but no avail.

**Comment by FGrose** [comment]
Pull request #45 fixes this and some other oversights.

**Comment by Conan-Kudo** [comment]
Fixed with merging of #45.
