### ISSUE TITLE
Patch to set default label to linux and to remove boot.msg using new arguments

### ISSUE THREAD

**Issue by havealoha** [livecd-tools/livecd-tools#54]
Attached patch to set default label to linux and to remove boot.msg using arguments.

Not all live iso's destined for disc are intended for installation nor do we want to require input during boot. Lets add something like this patch so the disc boots straight away.

[livecd-iso-to-disk.sh.zip](https://github.com/livecd-tools/livecd-tools/files/865816/livecd-iso-to-disk.sh.zip)

**Comment by FGrose** [comment]
Accomplished with pull request #55 .

**Comment by Conan-Kudo** [comment]
Merged in with 4598f65b4aeac59ac7fba89ff0c86641b52b5ee5.
