### ISSUE TITLE
Feature Request - Allow livecd creation from Chroot folder.

### ISSUE THREAD

**Issue by jmiahman** [livecd-tools/livecd-tools#68]
It would be nice to allow livecd creation from a chroot folder. You can create a chroot folder multiple ways and have more control over what's in it without needing mock or other tools like kickstart to create a chroot environment. It would be nice to have the option to just point to a chroot dir and go from there. If there's something else in redhat/fedora land that allows this let me know. Thanks

**Comment by Conan-Kudo** [comment]
@jmiahman I'm not exactly sure what you're asking for?

**Comment by jmiahman** [comment]
From my limited understanding.. it would seem as though a kickstart file is used to kickoff mock and create a chroot do the changes that are in a the ks at that point the chroot gets added to a disk image squashed via mksquashfs, the directory structure for an ISO gets built and the newly compressed image gets added to LiveOS/squashfs.img for which then during boot the dmsquashfs-live-root script picks up mounts and pivots root and calls the init so it can boot.

I want to skip the kickstart part and just supply my own chroot.. the path to a folder that already has my tweaks etc.. and allow lived tools etc.. to then pick it up from there create a disk image with it and add it to a live cd.

**Comment by Conan-Kudo** [comment]
@jmiahman If you want to do that, you probably want to leverage the `imgcreate` Python module to bypass the normal build flow.

**Comment by jmiahman** [comment]
What I was trying to accomplish has actually been solved with the recent addition of flattened squashfs images.

**Comment by Conan-Kudo** [comment]
Oh, good. 💯
