### ISSUE TITLE
what rev should I use for RHEL 7?

### ISSUE THREAD

**Issue by simpsonar77** [livecd-tools/livecd-tools#69]
I used to use livecd-tools for USB creation in RHEl 6.  worked so well.  Under RHEL 7, I've not been able to use it.  I'm trying it again, but notice the use of dnf vs yum.  is there a specific version I should be going back to for RHEL 7.3/4?

Also, if I don't want to create a "LIVE" version, will this tool allow me to do that?  sorry for noobish questions, just now reading through the source.  

(Sorry, I know this isn't an "issue", but the fedora mailing list is full of spam.)

**Comment by bcl** [comment]
RHEL7 includes livemedia-creator, the replacement for livecd-creator. It is part of the lorax package. Documentation can be found here: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/sect-disk-image-installation-automatic.html

**Comment by simpsonar77** [comment]
that's pretty helpful.  wasn't aware.

However, the only thing it doesn't do that I liked about livecd-tools was
actually push to a USB drive.  I currently use DD in my scripts, but
prefered the way livecd-tools did it.

I'll give this a shot.

**Comment by bcl** [comment]
You should still be able to use livecd-iso-to-disk on the created isos.

**Comment by Conan-Kudo** [comment]
@simpsonar77 If you want to use livecd-tools with RHEL 7, you should be able to use v23 with it, as that supports Yum (v24 was the first to use DNF instead).
