### ISSUE TITLE
cryptsetup is not in the dependencies

### ISSUE THREAD

**Issue by ashegoulding** [livecd-tools/livecd-tools#7]
On line 1330 in livecd-iso-to-disk, the script invokes 'cryptsetup' which doesn't come with the package as a dependency.
Hence running this script on minimal installation of Fedora causes error when it reaches "/home" initialize phase. This problem can be resolved by installing cryptsetup package.

**Comment by ashegoulding** [comment]
Issued on Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1238696

**Comment by Conan-Kudo** [comment]
Fixed downstream in Fedora.
