### ISSUE TITLE
livecd-iso-to-disk: usb not bootable with F26

### ISSUE THREAD

**Issue by ramseybrenner** [livecd-tools/livecd-tools#70]
Started F26 WS 64-bit from a live USB (created with dd), and installed livecd-tools from the repo (version 24.4-1.fc26). Created a USB using:

sudo livecd-iso-to-disk --format /run/initramfs/livedev /dev/sdb

Results in an unbootable usb. I just get a black screen with a blinking cursor.

**Comment by FGrose** [comment]
Try resetting the master boot record with the --reset-mbr option.
See https://fedoraproject.org/wiki/How_to_create_and_use_Live_USB#Command_line_method:_Using_the_livecd-iso-to-disk_tool_.28Fedora_only.2C_non-graphical.2C_both_non-destructive_and_destructive_methods_available.29

**Comment by ramseybrenner** [comment]
That was it. Of course it was user error. Thanks for the pointer
