### ISSUE TITLE
edit-livecd aborted with error: AttributeError: 'LiveImageEditor' object has no attribute '_ImageCreator__fstype'

### ISSUE THREAD

**Issue by vmurashev** [livecd-tools/livecd-tools#71]
edit-livecd aborted with error: AttributeError: 'LiveImageEditor' object has no attribute '_ImageCreator__fstype'

How to reproduce:
1) Install latest Fedora release from official Fedora-Workstation-Live-x86_64-26-1.5.iso
2) do ' yum install livecd-tools'
3) call 'edit-livecd Fedora-Workstation-Live-x86_64-26-1.5.iso --verbose'
4) And the error is here:
[root@acrotest-1809fc me]# edit-livecd Fedora-Workstation-Live-x86_64-26-1.5.iso --verbose
Fedora-Workstation-Live-x86_64-26-1.5.iso
Losetup add /dev/loop0 mapping to Fedora-Workstation-Live-x86_64-26-1.5.iso
Mounting /dev/loop0 at /var/tmp/edit-liveos-1aoa_fwy/tmp-vlj7pt8c
Losetup add /dev/loop1 mapping to /var/tmp/edit-liveos-1aoa_fwy/tmp-vlj7pt8c/LiveOS/squashfs.img
Mounting /dev/loop1 at /var/tmp/edit-liveos-1aoa_fwy/tmp-80c6v_1t
Unmounting directory /var/tmp/edit-liveos-1aoa_fwy/tmp-80c6v_1t
Losetup remove /dev/loop1
Unmounting directory /var/tmp/edit-liveos-1aoa_fwy/tmp-vlj7pt8c
Losetup remove /dev/loop0
Error editing LiveOS : 'Fedora-Workstation-Live-x86_64-26-1.5.iso' is not a valid live CD ISO : neither LiveOS/ext3fs.img nor os.img exist

**Comment by Conan-Kudo** [comment]
So it's `squashfs.img` now?
