### ISSUE TITLE
Move to pykickstart-3

### ISSUE THREAD

**Issue by clumens** [livecd-tools/livecd-tools#85]
Over the past two years, I've been working on a new version of pykickstart that cleans up a bunch of stuff and corrects some inherent flaws, as well as stops using certain deprecated python modules. The result is that there are some incompatibilities between v2 and v3. The projects that are most affected are the ones that really dig in and do a lot of custom stuff. It's been in the works a long time now and with anaconda starting to adapt, I feel like it's probably time to get rid of pykickstart-2 and use pykickstart-3 in Fedora.

There is a copr with the new version here: https://copr.fedorainfracloud.org/coprs/clumens/pykickstart-3/, and there's a document describing the changes here: https://github.com/rhinstaller/pykickstart/blob/master/docs/2to3.

imgcreate looks like it uses pykickstart only moderately, so with some luck there's almost nothing to do here.  However, I'd be happy to develop any patches required if you can give me some idea how to best test them out.

**Comment by Conan-Kudo** [comment]
@clumens Patches/pulls to migrate to pykickstart-3 are definitely welcome. pykickstart2 has been rather annoying to work with :/

The main way I've been testing is just attempting to produce Fedora and Mageia ISOs with it. If all of that works, then I usually call it good.

The other bit to verify is that Fedora ARM images still build with appliance-tools, as that depends on this code, too.

**Comment by clumens** [comment]
pykickstart-3 probably doesn't fix whatever you find annoying about pykickstart-2, unfortunately.  I'd be happy to listen to what you find annoying and potentially make changes, though.  We could do that via email, or a pykickstart issue, or whatever.

Can I just follow the README to try making a Fedora image, or is there something else I should do?

**Comment by Conan-Kudo** [comment]
Yeah, the README should work. You may also want to try some of the official Fedora kickstarts (I test with Workstation's). I periodically test with @kkofler's Kannolo kickstart, too: https://svn.calcforge.org/viewvc/kannolo/trunk/kickstart/kannolo.ks?view=markup

**Comment by clumens** [comment]
So far, the only change I have had to make is to remove get_modules from kickstart.py and its call from live.py.

I've run it against that kickstart file which produced an image (which I have not tried to run), and I've gone through my 2to3 doc to see if any of the stuff in there is in use - it's not.  I'm not sure what else I need to do to verify things work.  From looking through the code again I feel there's likely some attributes being looked for that haven't existed in pykickstart for a long while, but I don't think they are causing problems and I'm not sure how far down that path I want to go.

**Comment by Conan-Kudo** [comment]
My main annoyance is the involuntary deprecation warnings being printed from within pykickstart2. So if those go away, I'll be just dandy.

**Comment by Conan-Kudo** [comment]
@clumens As long as you can build a real, working Fedora image from one of the official spins/editions as well as a bootable minimal one, then I'm happy to accept a pull request with the changes.

**Comment by clumens** [comment]
Yeah, the deprecation warnings have been a problem.  I don't know what version you are using, but https://github.com/rhinstaller/pykickstart/commit/6aa4207d4683920a2399a50d1f1347d061ae4c5a should have taken care of most of those.  I'd have to check out a log file to see what else could be going on.

**Comment by dcantrell** [comment]
I've sent a pull request to livecd-tools to address the issues I ran in to running the master version against the latest pykickstart 3.9 build on Fedora 27.  https://github.com/livecd-tools/livecd-tools/pull/92

With those patches in place, livecd-creator generates a usable iso for me using the example ks file.

**Comment by Conan-Kudo** [comment]
@clumens @dcantrell Should I now consider this fixed with the current master?

**Comment by clumens** [comment]
Yep, it should be all good now - any problems that arise should probably be handled as new bugs either in livecd-tools or in pykickstart.  Thanks.
