### ISSUE TITLE
Move from genisoimage to xorriso

### ISSUE THREAD

**Issue by Conan-Kudo** [livecd-tools/livecd-tools#97]
`genisoimage` (from `cdrkit`) is old and unmaintained. These days, the modern replacement available is from [`xorriso`](https://www.gnu.org/software/xorriso/), which looks like it supports all the features that exist in our variant of `genisoimage`.

We should switch from `genisoimage` to `xorriso`.

**Comment by bcl** [comment]
Watch out for problems with the EFI image and hybridiso. Last year I accidentally ended up with xorriso on my system and lorax was failing with isohybrid complaining it couldn't find the mac efi image. At the time I removed it and reinstalled genisoimage and moved on.

**Comment by Conan-Kudo** [comment]
@bcl I had the same thing happen to me, which is why I did this change: https://github.com/livecd-tools/livecd-tools/commit/dbd94def9c102b7cd643ead6af15922774d2d0d9

However, unless someone wants to properly take up maintaining cdrkit, we're all in a bad spot.

**Comment by Conan-Kudo** [comment]
Experimental branch with using xorriso is now live: https://github.com/livecd-tools/livecd-tools/commits/change-to-xorriso

**Comment by Conan-Kudo** [comment]
This is now complete with 686e5b63111ba40319c7a42d0ec966260d43d2a9.

Single-stage hybridization was implemented in 320d92a8cdb692f704ce83895bd921450522e946.
